### ISSUE TITLE
Need to add Travis CI token

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-maps/new_world_order-skin_gudkarma_1#1]

**Comment by DanVanAtta** [comment]
this needs removal first:
https://github.com/triplea-maps/new_world_order-skin_gudkarma_1/tree/master/map/flags/Swastica%20skin

**Comment by DanVanAtta** [comment]
Actually, wait, we aren't doing travis CI token anymore in favor of having 'master' zip. Is there actually anything to do here for this issue?

**Comment by ron-murhammer** [comment]
@DanVanAtta Removed.  So what triggers the releases then? As it doesn't appear it triggering any.

**Comment by DanVanAtta** [comment]
The 'master' url is static and pinned to the latest master. The travis build before was mostly to build a zip file. We can get the same zip from the 'master' url. The game engine was updated to allow parsing that folder format. We no longer strictly need travis to add maps in now.

**Comment by DanVanAtta** [comment]
Happy to answer any further questions, please cut an issue in the game-engine repo for follow up (so we don't bury the conversation here)
